### ISSUE TITLE
Problem with the VS Code Payara extension.

### ISSUE THREAD

**Issue by k-d-ivanov** [payara/ecosystem-vscode-plugin#30]
Hello. 

My problem is that when I click "Run on Payara Server", only Payara Server started and NO *.war file/s are generated or deployed to the started server, no browses are automaticaly oppedned too(as the tutorial stated).

I'm using VS Code on Windows 10. I have installed "Java Extension Pack",  latest Maven 3.6.3, Payara Server 5.201. All VS Code extensions are up to date.

The files attached are output window of VS Code, when I hit Run on Payara, and the pom.xml fiile of the project.

Best Regards, Kiril.

[VSCode_Payara _extension_issue.zip](https://github.com/payara/ecosystem-vscode-plugin/files/4489267/VSCode_Payara._extension_issue.zip)

**Comment by jGauravGupta** [comment]
Hi @k-d-ivanov,

I tried to reproduce the issue using the attached `pom.xml` but application build and deployed successfully to Payara Server. 
Can you please share the log of VSCode Developer Console, you may open this window from **Help menu > Toggle Developer Tools > Console tab**. Also when you click "Run on Payara Server" an output window is opened with the name of the respective project to build it, May you also share the log of the project output window?

**Comment by k-d-ivanov** [comment]
Hello. I'm happy to tell you that the problem is fixed.  Thank you for telling me for the "Developer tools menu" where I found that my paths where wrong( "C:\Program Files..." for example).
Thanks again for your help.
Best Regards.

**Comment by jGauravGupta** [comment]
Still, this is an issue, please share the log of VSCode Developer Console.

**Comment by k-d-ivanov** [comment]
Ok. Those are the logs you'he asked for. After I fixed my windows environment paths (for Java and Maven) with
C:\Progra~1\.... instead of C:\Program Files\.....

Thanks. 

[DevToolsConsole_log.txt](https://github.com/payara/ecosystem-vscode-plugin/files/4547377/DevToolsConsole_log.txt)
[vscode_project_log.txt](https://github.com/payara/ecosystem-vscode-plugin/files/4547378/vscode_project_log.txt)

**Comment by jGauravGupta** [comment]
Thanks @k-d-ivanov for the logs.

**Comment by jGauravGupta** [comment]
Created an internal ticket [ECOSYS-154](https://payara.atlassian.net/browse/ECOSYS-154) to address the issue.

**Comment by alcarnes** [comment]
This is not working with visual studio code under linux.

[DevToolsConsole_log.txt](https://github.com/payara/ecosystem-vscode-plugin/files/4658825/DevToolsConsole_log.txt)

**Comment by jGauravGupta** [comment]
Hi @k-d-ivanov / @alcarnes,

Can you please review the PR and share your valuable feedback.

**Comment by k-d-ivanov** [comment]
It is working on my setup. Thanks

**Comment by alcarnes** [comment]
This is still not working on my configuration.  Starting the payara server from within gives the error I attached above.  Then when I click on run on payara server it doesn't do anything.  There is no additional output to the DevToolsConsole. I followed  [this tutorial](https://blog.payara.fish/adding-payara-server-to-visual-studio-code)

**Comment by alcarnes** [comment]
`
log.ts:197   ERR spawn tail  ENOENT: Error: spawn tail  ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
extensionHost.ts:222 Extension Host
extensionHost.ts:223 {
  message: 'Starting Java server with: /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/acarnes/.vscode/extensions/redhat.java-0.62.0/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/acarnes/.config/Code/User/globalStorage/redhat.java/0.62.0/config_ss_linux -data /home/acarnes/.config/Code/User/workspaceStorage/157bcd592f9c261c744bf6868ca9b8ea/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2020-06-11 13:42:55.938'
}
{
  message: 'Starting Java server with: /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/acarnes/.vscode/extensions/redhat.java-0.62.0/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/acarnes/.config/Code/User/globalStorage/redhat.java/0.62.0/config_linux -data /home/acarnes/.config/Code/User/workspaceStorage/157bcd592f9c261c744bf6868ca9b8ea/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2020-06-11 13:42:55.952'
}
viewLine.ts:418 monospace assumptions have been violated, therefore disabling monospace optimizations!
2
console.ts:137 [Extension Host] (node:66316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: message.property is not iterable
console.ts:137 [Extension Host] stack trace: TypeError: message.property is not iterable
	at PayaraServerInstance.<anonymous> (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/out/main/fish/payara/server/PayaraServerInstance.js:310:46)
	at Generator.next (<anonymous>)
	at /home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/out/main/fish/payara/server/PayaraServerInstance.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/out/main/fish/payara/server/PayaraServerInstance.js:4:12)
	at /home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/out/main/fish/payara/server/PayaraServerInstance.js:307:69
	at /home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/out/main/fish/payara/server/endpoints/RestEndpoints.js:36:29
	at Parser.<anonymous> (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/xml2js/lib/parser.js:304:18)
	at Parser.emit (events.js:203:13)
	at SAXParser.onclosetag (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/xml2js/lib/parser.js:262:26)
	at emit (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/sax/lib/sax.js:624:35)
	at emitNode (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/sax/lib/sax.js:629:5)
	at closeTag (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/sax/lib/sax.js:889:7)
	at SAXParser.write (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/sax/lib/sax.js:1436:13)
	at Parser.exports.Parser.Parser.parseString (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/xml2js/lib/parser.js:323:31)
	at Parser.parseString (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/node_modules/xml2js/lib/parser.js:5:59)
	at IncomingMessage.<anonymous> (/home/acarnes/.vscode/extensions/payara.payara-vscode-0.0.3/out/main/fish/payara/server/endpoints/RestEndpoints.js:32:41)
	at IncomingMessage.emit (events.js:203:13)
	at IncomingMessage.Readable.read (_stream_readable.js:515:10)
	at flow (_stream_readable.js:984:34)
	at resume_ (_stream_readable.js:965:3)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
mainThreadExtensionService.ts:65 [[object Object]]message.property is not iterable
mainThreadExtensionService.ts:66 TypeError: message.property is not iterable
	at PayaraServerInstance.<anonymous> (/home/acarnes/.vscod…rverInstance.js:310)
	at Generator.next (<anonymous>)
	at /home/acarnes/.vscod…ServerInstance.js:8
	at new Promise (<anonymous>)
	at __awaiter (/home/acarnes/.vscod…ServerInstance.js:4)
	at /home/acarnes/.vscod…rverInstance.js:307
	at /home/acarnes/.vscod…RestEndpoints.js:36
	at Parser.<anonymous> (/home/acarnes/.vscod…s/lib/parser.js:304)
	at Parser.emit (events.js:203)
	at SAXParser.onclosetag (/home/acarnes/.vscod…s/lib/parser.js:262)
	at emit (/home/acarnes/.vscod…/sax/lib/sax.js:624)
	at emitNode (/home/acarnes/.vscod…/sax/lib/sax.js:629)
	at closeTag (/home/acarnes/.vscod…/sax/lib/sax.js:889)
	at SAXParser.write (/home/acarnes/.vscod…sax/lib/sax.js:1436)
	at Parser.exports.Parser.Parser.parseString (/home/acarnes/.vscod…s/lib/parser.js:323)
	at Parser.parseString (/home/acarnes/.vscod…2js/lib/parser.js:5)
	at IncomingMessage.<anonymous> (/home/acarnes/.vscod…RestEndpoints.js:32)
	at IncomingMessage.emit (events.js:203)
	at IncomingMessage.Readable.read (_stream_readable.js:515)
	at flow (_stream_readable.js:984)
	at resume_ (_stream_readable.js:965)`

**Comment by alcarnes** [comment]
[DevToolsConsole.txt](https://github.com/payara/ecosystem-vscode-plugin/files/4767235/DevToolsConsole.txt)
Here is a copy of devtoolsconsole that I spread out so you could see the full paths/files.
