### ISSUE TITLE
Add Local Server on MacOS using OpenJDK

### ISSUE THREAD

**Issue by a-solano** [payara/ecosystem-vscode-plugin#50]
Hello Payara team. Actually I'm making some test using VScode and Payara 5. But when I try to create a new Payara server, and select the domain the Extension can't continue.

I downloaded the code and the debug console show me:

```
_stack trace: Error: Command failed: /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/bin/jps -mlv
	at checkExecSyncError (child_process.js:634:11)
	at Object.execFileSync (child_process.js:652:15)
	at Object.func [as execFileSync] (electron/js2c/asar.js:140:31)
	at PayaraLocalServerInstance.checkAliveStatusUsingJPS (/Users/asolano/Code/extensions/ecosystem-vscode-plugin/out/main/fish/payara/server/PayaraLocalServerInstance.js:110:25)
	at registerServer (/Users/asolano/Code/extensions/ecosystem-vscode-plugin/out/main/fish/payara/server/PayaraServerInstanceController.js:93:42)
	at /Users/asolano/Code/extensions/ecosystem-vscode-plugin/out/main/fish/payara/server/PayaraServerInstanceController.js:121:25
	at PayaraServerInstanceController.<anonymous> (/Users/asolano/Code/extensions/ecosystem-vscode-plugin/out/main/fish/payara/server/PayaraServerInstanceController.js:342:13)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/asolano/Code/extensions/ecosystem-vscode-plugin/out/main/fish/payara/server/PayaraServerInstanceController.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)_
```

I notice that the file src/main/fish/payara/server/PayaraLocalServerInstance.ts at line 122 actually is: 

`let output: string = cp.execFileSync(javaProcessExe, ['-mlv']);`

Can you change it to:

`let output: string = cp.execFileSync(javaProcessExe, ['-m', '-l', '-v']);`

Let me know yours comments.

Regards.

**Comment by samderlust** [comment]
did you resolve this?

**Comment by jGauravGupta** [comment]
Created internal ticket FISH-489 to address it.

**Comment by alhassan-fadel** [comment]
The same issue appears on Linux (Ubuntu 20.04) as well
